#!/usr/bin/env bash

sudo apt update -y

curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
sudo apt install -y nodejs

rm -rf node_modules
rm package-lock.json package.json tailwind.config.js postcss.config.js

npm init -y
npm install tailwindcss postcss-cli autoprefixer
npx tailwind init

touch postcss.config.js
echo "
module.exports= {
        plugins: [
                require("tailwindcss"),
                require("autoprefixer"),
        ]
}
" >> postcss.config.js

